//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class internshipEntities2 : DbContext
    {
        public internshipEntities2()
            : base("name=internshipEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<convention> convention { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<document> document { get; set; }
        public virtual DbSet<eclass> eclass { get; set; }
        public virtual DbSet<enterprise> enterprise { get; set; }
        public virtual DbSet<final_project_assignment> final_project_assignment { get; set; }
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<notification> notification { get; set; }
        public virtual DbSet<options> options { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sheet> sheet { get; set; }
        public virtual DbSet<university> university { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<validation_group> validation_group { get; set; }
    }
}
