//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date_fichier_alf { get; set; }
        public byte[] fichier_alfresco { get; set; }
        public string format_fichier_alf { get; set; }
        public string id_fichier_alf { get; set; }
        public string nom_fichier_alf { get; set; }
        public string path_fichier_alf { get; set; }
        public Nullable<bool> present { get; set; }
        public Nullable<long> size_fichier_alf { get; set; }
        public Nullable<long> final_project_assignment_id { get; set; }
    
        public virtual final_project_assignment final_project_assignment { get; set; }
    }
}
