//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enterprise
    {
        public long id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string street { get; set; }
        public long zip_code { get; set; }
        public string domain { get; set; }
        public string email { get; set; }
        public string email_supervisor { get; set; }
        public string name { get; set; }
        public string web_site { get; set; }
        public Nullable<long> representative_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
