//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_project_assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public final_project_assignment()
        {
            this.document = new HashSet<document>();
        }
    
        public long id { get; set; }
        public long convention_name { get; set; }
        public long sheet_id { get; set; }
        public long student_id { get; set; }
        public Nullable<long> validation_group_id { get; set; }
    
        public virtual convention convention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> document { get; set; }
        public virtual validation_group validation_group { get; set; }
        public virtual users users { get; set; }
        public virtual sheet sheet { get; set; }
    }
}
