//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public long id { get; set; }
        public string level { get; set; }
        public string note { get; set; }
        public double number { get; set; }
        public long maker_id { get; set; }
        public long sheet_id { get; set; }
    
        public virtual users users { get; set; }
        public virtual sheet sheet { get; set; }
    }
}
