//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public long id { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> sys_notif_date { get; set; }
        public Nullable<long> owner_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
