//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class options
    {
        public long id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string label { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<long> department_id { get; set; }
    
        public virtual department department { get; set; }
    }
}
