//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sheet()
        {
            this.final_project_assignment = new HashSet<final_project_assignment>();
            this.grade = new HashSet<grade>();
        }
    
        public long id { get; set; }
        public string categorie { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string description { get; set; }
        public byte[] enterprise { get; set; }
        public string problematique { get; set; }
        public string project_title { get; set; }
        public string student_name { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<final_project_assignment> final_project_assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grade> grade { get; set; }
    }
}
